name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: |
          echo "Hello World 1"
          echo "Hello World 2"
          echo "Hello World 3"
      - name: Print goodbye
        run: echo "goodbye"
